serviceName: transport
Port: "8081"
Clusters:
  - Input:
      Kafka:
        Name: "kf"
        Brokers:
          - "127.0.0.1:9092"
        Topics:
          - news-data
        Group: news
        Consumers: 16
    Output:
      ElasticSearch:
        Hosts:
          - http://127.0.0.1:9200
        Index: "news_test"
